name: Publish Node.js Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checking out source code
        uses: actions/checkout@v3

      - name: Setting up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Publishing
        shell: bash
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"                 > .npmrc
          echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com/" >> .npmrc
          chmod 0600 .npmrc
          npm publish
